# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-0ffd4636-7b4c-4b8a-8d8c-c182ab32990c";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-0ffd4636-7b4c-4b8a-8d8c-c182ab32990c".device = "/dev/disk/by-uuid/0ffd4636-7b4c-4b8a-8d8c-c182ab32990c";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BD72-E711";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-d37d0d29-9ed6-4388-a590-8938e0ef5911"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
